// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ShardAccepted
	//	*AgentMessage_ShardStarted
	//	*AgentMessage_ShardCompleted
	//	*AgentMessage_ShardFailed
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetShardAccepted() *ShardAccepted {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ShardAccepted); ok {
			return x.ShardAccepted
		}
	}
	return nil
}

func (x *AgentMessage) GetShardStarted() *ShardStarted {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ShardStarted); ok {
			return x.ShardStarted
		}
	}
	return nil
}

func (x *AgentMessage) GetShardCompleted() *ShardCompleted {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ShardCompleted); ok {
			return x.ShardCompleted
		}
	}
	return nil
}

func (x *AgentMessage) GetShardFailed() *ShardFailed {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ShardFailed); ok {
			return x.ShardFailed
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ShardAccepted struct {
	ShardAccepted *ShardAccepted `protobuf:"bytes,3,opt,name=shard_accepted,json=shardAccepted,proto3,oneof"`
}

type AgentMessage_ShardStarted struct {
	ShardStarted *ShardStarted `protobuf:"bytes,4,opt,name=shard_started,json=shardStarted,proto3,oneof"`
}

type AgentMessage_ShardCompleted struct {
	ShardCompleted *ShardCompleted `protobuf:"bytes,5,opt,name=shard_completed,json=shardCompleted,proto3,oneof"`
}

type AgentMessage_ShardFailed struct {
	ShardFailed *ShardFailed `protobuf:"bytes,6,opt,name=shard_failed,json=shardFailed,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_ShardAccepted) isAgentMessage_Payload() {}

func (*AgentMessage_ShardStarted) isAgentMessage_Payload() {}

func (*AgentMessage_ShardCompleted) isAgentMessage_Payload() {}

func (*AgentMessage_ShardFailed) isAgentMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_AssignShard
	//	*ServerMessage_Drain
	//	*ServerMessage_Shutdown
	//	*ServerMessage_CancelShard
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetAssignShard() *AssignShard {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_AssignShard); ok {
			return x.AssignShard
		}
	}
	return nil
}

func (x *ServerMessage) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *ServerMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ServerMessage) GetCancelShard() *CancelShard {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CancelShard); ok {
			return x.CancelShard
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_AssignShard struct {
	AssignShard *AssignShard `protobuf:"bytes,1,opt,name=assign_shard,json=assignShard,proto3,oneof"`
}

type ServerMessage_Drain struct {
	Drain *Drain `protobuf:"bytes,2,opt,name=drain,proto3,oneof"`
}

type ServerMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"`
}

type ServerMessage_CancelShard struct {
	CancelShard *CancelShard `protobuf:"bytes,4,opt,name=cancel_shard,json=cancelShard,proto3,oneof"`
}

func (*ServerMessage_AssignShard) isServerMessage_Payload() {}

func (*ServerMessage_Drain) isServerMessage_Payload() {}

func (*ServerMessage_Shutdown) isServerMessage_Payload() {}

func (*ServerMessage_CancelShard) isServerMessage_Payload() {}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BackendName   string                 `protobuf:"bytes,3,opt,name=backend_name,json=backendName,proto3" json:"backend_name,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Register) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Register) GetBackendName() string {
	if x != nil {
		return x.BackendName
	}
	return ""
}

func (x *Register) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Register) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentShardId string                 `protobuf:"bytes,3,opt,name=current_shard_id,json=currentShardId,proto3" json:"current_shard_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetCurrentShardId() string {
	if x != nil {
		return x.CurrentShardId
	}
	return ""
}

type AssignShard struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ShardId            string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	TaskId             string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BundleArtifactId   string                 `protobuf:"bytes,3,opt,name=bundle_artifact_id,json=bundleArtifactId,proto3" json:"bundle_artifact_id,omitempty"`
	InputCsvArtifactId string                 `protobuf:"bytes,4,opt,name=input_csv_artifact_id,json=inputCsvArtifactId,proto3" json:"input_csv_artifact_id,omitempty"`
	ShardIndex         int32                  `protobuf:"varint,5,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	TotalShards        int32                  `protobuf:"varint,6,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AssignShard) Reset() {
	*x = AssignShard{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignShard) ProtoMessage() {}

func (x *AssignShard) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignShard.ProtoReflect.Descriptor instead.
func (*AssignShard) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *AssignShard) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *AssignShard) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignShard) GetBundleArtifactId() string {
	if x != nil {
		return x.BundleArtifactId
	}
	return ""
}

func (x *AssignShard) GetInputCsvArtifactId() string {
	if x != nil {
		return x.InputCsvArtifactId
	}
	return ""
}

func (x *AssignShard) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

func (x *AssignShard) GetTotalShards() int32 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

type CancelShard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShard) Reset() {
	*x = CancelShard{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShard) ProtoMessage() {}

func (x *CancelShard) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShard.ProtoReflect.Descriptor instead.
func (*CancelShard) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *CancelShard) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type ShardAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardAccepted) Reset() {
	*x = ShardAccepted{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardAccepted) ProtoMessage() {}

func (x *ShardAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardAccepted.ProtoReflect.Descriptor instead.
func (*ShardAccepted) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *ShardAccepted) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type ShardStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardStarted) Reset() {
	*x = ShardStarted{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardStarted) ProtoMessage() {}

func (x *ShardStarted) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardStarted.ProtoReflect.Descriptor instead.
func (*ShardStarted) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *ShardStarted) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type ShardCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	OutputCsv     []byte                 `protobuf:"bytes,2,opt,name=output_csv,json=outputCsv,proto3" json:"output_csv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardCompleted) Reset() {
	*x = ShardCompleted{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardCompleted) ProtoMessage() {}

func (x *ShardCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardCompleted.ProtoReflect.Descriptor instead.
func (*ShardCompleted) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *ShardCompleted) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardCompleted) GetOutputCsv() []byte {
	if x != nil {
		return x.OutputCsv
	}
	return nil
}

type ShardFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardFailed) Reset() {
	*x = ShardFailed{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardFailed) ProtoMessage() {}

func (x *ShardFailed) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardFailed.ProtoReflect.Descriptor instead.
func (*ShardFailed) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *ShardFailed) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardFailed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type FetchArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchArtifactRequest) Reset() {
	*x = FetchArtifactRequest{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchArtifactRequest) ProtoMessage() {}

func (x *FetchArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchArtifactRequest.ProtoReflect.Descriptor instead.
func (*FetchArtifactRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *FetchArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type FetchArtifactChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchArtifactChunk) Reset() {
	*x = FetchArtifactChunk{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchArtifactChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchArtifactChunk) ProtoMessage() {}

func (x *FetchArtifactChunk) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchArtifactChunk.ProtoReflect.Descriptor instead.
func (*FetchArtifactChunk) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *FetchArtifactChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x18rorchestrator.control.v1\"\xe2\x03\n" +
	"\fAgentMessage\x12@\n" +
	"\bregister\x18\x01 \x01(\v2\".rorchestrator.control.v1.RegisterH\x00R\bregister\x12C\n" +
	"\theartbeat\x18\x02 \x01(\v2#.rorchestrator.control.v1.HeartbeatH\x00R\theartbeat\x12P\n" +
	"\x0eshard_accepted\x18\x03 \x01(\v2'.rorchestrator.control.v1.ShardAcceptedH\x00R\rshardAccepted\x12M\n" +
	"\rshard_started\x18\x04 \x01(\v2&.rorchestrator.control.v1.ShardStartedH\x00R\fshardStarted\x12S\n" +
	"\x0fshard_completed\x18\x05 \x01(\v2(.rorchestrator.control.v1.ShardCompletedH\x00R\x0eshardCompleted\x12J\n" +
	"\fshard_failed\x18\x06 \x01(\v2%.rorchestrator.control.v1.ShardFailedH\x00R\vshardFailedB\t\n" +
	"\apayload\"\xad\x02\n" +
	"\rServerMessage\x12J\n" +
	"\fassign_shard\x18\x01 \x01(\v2%.rorchestrator.control.v1.AssignShardH\x00R\vassignShard\x127\n" +
	"\x05drain\x18\x02 \x01(\v2\x1f.rorchestrator.control.v1.DrainH\x00R\x05drain\x12@\n" +
	"\bshutdown\x18\x03 \x01(\v2\".rorchestrator.control.v1.ShutdownH\x00R\bshutdown\x12J\n" +
	"\fcancel_shard\x18\x04 \x01(\v2%.rorchestrator.control.v1.CancelShardH\x00R\vcancelShardB\t\n" +
	"\apayload\"\x95\x01\n" +
	"\bRegister\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fbackend_name\x18\x03 \x01(\tR\vbackendName\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"h\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12(\n" +
	"\x10current_shard_id\x18\x03 \x01(\tR\x0ecurrentShardId\"\xe6\x01\n" +
	"\vAssignShard\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12,\n" +
	"\x12bundle_artifact_id\x18\x03 \x01(\tR\x10bundleArtifactId\x121\n" +
	"\x15input_csv_artifact_id\x18\x04 \x01(\tR\x12inputCsvArtifactId\x12\x1f\n" +
	"\vshard_index\x18\x05 \x01(\x05R\n" +
	"shardIndex\x12!\n" +
	"\ftotal_shards\x18\x06 \x01(\x05R\vtotalShards\"\a\n" +
	"\x05Drain\"\n" +
	"\n" +
	"\bShutdown\"(\n" +
	"\vCancelShard\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"*\n" +
	"\rShardAccepted\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\")\n" +
	"\fShardStarted\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"J\n" +
	"\x0eShardCompleted\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x1d\n" +
	"\n" +
	"output_csv\x18\x02 \x01(\fR\toutputCsv\"M\n" +
	"\vShardFailed\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"7\n" +
	"\x14FetchArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"(\n" +
	"\x12FetchArtifactChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xeb\x01\n" +
	"\x0eControlService\x12h\n" +
	"\x11OpenControlStream\x12&.rorchestrator.control.v1.AgentMessage\x1a'.rorchestrator.control.v1.ServerMessage(\x010\x01\x12o\n" +
	"\rFetchArtifact\x12..rorchestrator.control.v1.FetchArtifactRequest\x1a,.rorchestrator.control.v1.FetchArtifactChunk0\x01B3Z1github.com/yichozy/r-orchestrator/proto/controlv1b\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_control_proto_goTypes = []any{
	(*AgentMessage)(nil),         // 0: rorchestrator.control.v1.AgentMessage
	(*ServerMessage)(nil),        // 1: rorchestrator.control.v1.ServerMessage
	(*Register)(nil),             // 2: rorchestrator.control.v1.Register
	(*Heartbeat)(nil),            // 3: rorchestrator.control.v1.Heartbeat
	(*AssignShard)(nil),          // 4: rorchestrator.control.v1.AssignShard
	(*Drain)(nil),                // 5: rorchestrator.control.v1.Drain
	(*Shutdown)(nil),             // 6: rorchestrator.control.v1.Shutdown
	(*CancelShard)(nil),          // 7: rorchestrator.control.v1.CancelShard
	(*ShardAccepted)(nil),        // 8: rorchestrator.control.v1.ShardAccepted
	(*ShardStarted)(nil),         // 9: rorchestrator.control.v1.ShardStarted
	(*ShardCompleted)(nil),       // 10: rorchestrator.control.v1.ShardCompleted
	(*ShardFailed)(nil),          // 11: rorchestrator.control.v1.ShardFailed
	(*FetchArtifactRequest)(nil), // 12: rorchestrator.control.v1.FetchArtifactRequest
	(*FetchArtifactChunk)(nil),   // 13: rorchestrator.control.v1.FetchArtifactChunk
}
var file_control_proto_depIdxs = []int32{
	2,  // 0: rorchestrator.control.v1.AgentMessage.register:type_name -> rorchestrator.control.v1.Register
	3,  // 1: rorchestrator.control.v1.AgentMessage.heartbeat:type_name -> rorchestrator.control.v1.Heartbeat
	8,  // 2: rorchestrator.control.v1.AgentMessage.shard_accepted:type_name -> rorchestrator.control.v1.ShardAccepted
	9,  // 3: rorchestrator.control.v1.AgentMessage.shard_started:type_name -> rorchestrator.control.v1.ShardStarted
	10, // 4: rorchestrator.control.v1.AgentMessage.shard_completed:type_name -> rorchestrator.control.v1.ShardCompleted
	11, // 5: rorchestrator.control.v1.AgentMessage.shard_failed:type_name -> rorchestrator.control.v1.ShardFailed
	4,  // 6: rorchestrator.control.v1.ServerMessage.assign_shard:type_name -> rorchestrator.control.v1.AssignShard
	5,  // 7: rorchestrator.control.v1.ServerMessage.drain:type_name -> rorchestrator.control.v1.Drain
	6,  // 8: rorchestrator.control.v1.ServerMessage.shutdown:type_name -> rorchestrator.control.v1.Shutdown
	7,  // 9: rorchestrator.control.v1.ServerMessage.cancel_shard:type_name -> rorchestrator.control.v1.CancelShard
	0,  // 10: rorchestrator.control.v1.ControlService.OpenControlStream:input_type -> rorchestrator.control.v1.AgentMessage
	12, // 11: rorchestrator.control.v1.ControlService.FetchArtifact:input_type -> rorchestrator.control.v1.FetchArtifactRequest
	1,  // 12: rorchestrator.control.v1.ControlService.OpenControlStream:output_type -> rorchestrator.control.v1.ServerMessage
	13, // 13: rorchestrator.control.v1.ControlService.FetchArtifact:output_type -> rorchestrator.control.v1.FetchArtifactChunk
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ShardAccepted)(nil),
		(*AgentMessage_ShardStarted)(nil),
		(*AgentMessage_ShardCompleted)(nil),
		(*AgentMessage_ShardFailed)(nil),
	}
	file_control_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_AssignShard)(nil),
		(*ServerMessage_Drain)(nil),
		(*ServerMessage_Shutdown)(nil),
		(*ServerMessage_CancelShard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
