package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"io"
	"strings"

	"github.com/google/uuid"
	"github.com/yichozy/r-orchestrator/graph/generated"
	"github.com/yichozy/r-orchestrator/graph/model"
	imodel "github.com/yichozy/r-orchestrator/internal/model"
	"github.com/yichozy/r-orchestrator/internal/service/task_service"
)

// SubmitTask is the resolver for the submitTask field.
func (r *mutationResolver) SubmitTask(ctx context.Context, input model.SubmitTaskInput) (*model.SubmitTaskResponse, error) {
	if strings.TrimSpace(input.TenantName) == "" {
		return nil, fmt.Errorf("tenant name is required")
	}

	zip_bytes, err := io.ReadAll(input.RZipFile.File)
	if err != nil {
		return nil, err
	}
	if len(zip_bytes) == 0 {
		return nil, fmt.Errorf("zip is required")
	}
	csv_bytes, err := io.ReadAll(input.ParametersCSVFile.File)
	if err != nil {
		return nil, err
	}
	if len(csv_bytes) == 0 {
		return nil, fmt.Errorf("csv is required")
	}

	completionHookURL := ""
	if input.CompletionHookURL != nil {
		completionHookURL = *input.CompletionHookURL
	}

	task_id, err := task_service.SubmitTask(ctx, task_service.SubmitTaskParams{
		TenantName:        input.TenantName,
		ZipBytes:          zip_bytes,
		CSVBytes:          csv_bytes,
		CompletionHookURL: completionHookURL,
	})
	if err != nil {
		return nil, err
	}

	return &model.SubmitTaskResponse{
		TaskID: task_id,
	}, nil
}

// CancelTask is the resolver for the cancelTask field.
func (r *mutationResolver) CancelTask(ctx context.Context, tenantName string, taskID uuid.UUID) (*model.CancelTaskPayload, error) {
	if err := task_service.CancelTask(ctx, tenantName, taskID); err != nil {
		return nil, err
	}

	return &model.CancelTaskPayload{
		TaskID: taskID,
		Status: imodel.TaskStatusCancelled,
	}, nil
}

// GetTaskByID is the resolver for the GetTaskByID field.
func (r *queryResolver) GetTaskByID(ctx context.Context, tenantName string, taskID uuid.UUID) (*model.Task, error) {
	task, err := task_service.GetTask(ctx, tenantName, taskID)
	if err != nil {
		return nil, err
	}

	return &model.Task{
		ID:         task.ID,
		TenantName: task.TenantName,
		Status:     task.Status,
		LastError:  task.LastError,
		CreatedAt:  task.CreatedAt,
		StartedAt:  task.StartedAt,
		FinishedAt: task.FinishedAt,
		ShardCount: task.ShardCount,
	}, nil
}

// GetTaskList is the resolver for the GetTaskList field.
func (r *queryResolver) GetTaskList(ctx context.Context, tenantName string, status *string) ([]*model.Task, error) {
	statusValue := ""
	if status != nil {
		statusValue = *status
	}

	tasks, err := task_service.ListTasks(ctx, tenantName, statusValue)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Task, 0, len(tasks))
	for _, task := range tasks {
		result = append(result, &model.Task{
			ID:         task.ID,
			TenantName: task.TenantName,
			Status:     task.Status,
			LastError:  task.LastError,
			CreatedAt:  task.CreatedAt,
			StartedAt:  task.StartedAt,
			FinishedAt: task.FinishedAt,
			ShardCount: task.ShardCount,
		})
	}

	return result, nil
}

// GetTaskResultCSV is the resolver for the GetTaskResultCSV field.
func (r *queryResolver) GetTaskResultCSV(ctx context.Context, tenantName string, taskID uuid.UUID) (*model.TaskResultCSV, error) {
	result, err := task_service.GetTaskResultCSV(ctx, tenantName, taskID)
	if err != nil {
		return nil, err
	}

	return &model.TaskResultCSV{
		TaskID:      result.TaskID,
		Filename:    result.Filename,
		ContentType: result.ContentType,
		CSVContent:  result.CSVContent,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
