package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	gqlmodel "github.com/yichozy/r-orchestrator/graph/model"
	"github.com/yichozy/r-orchestrator/internal/model"
	"github.com/yichozy/r-orchestrator/internal/orm"
	"github.com/yichozy/r-orchestrator/internal/orm/tenant_orm"
)

// CreateTenant is the resolver for the CreateTenant field.
func (r *mutationResolver) CreateTenant(ctx context.Context, input gqlmodel.CreateTenantInput) (*gqlmodel.Tenant, error) {
	db, err := orm.GetDB()
	if err != nil {
		return nil, err
	}

	if input.MaxAgents <= 0 {
		return nil, fmt.Errorf("max_agents must be positive")
	}

	tenant, err := tenant_orm.Create(ctx, db, model.Tenant{
		Name:               input.Name,
		PrimaryBackendName: input.PrimaryBackendName,
		MaxAgents:          input.MaxAgents,
	})
	if err != nil {
		return nil, err
	}

	return &gqlmodel.Tenant{
		ID:                 tenant.ID,
		Name:               tenant.Name,
		PrimaryBackendName: tenant.PrimaryBackendName,
		MaxAgents:          tenant.MaxAgents,
	}, nil
}
