replicaCount: 1

image:
  orchestrator:
    repository: registry-vpc.ap-southeast-1.aliyuncs.com/knewta/r-orchestrator
    tag: v0.1.0
    pullPolicy: IfNotPresent
  agent:
    repository: registry-vpc.ap-southeast-1.aliyuncs.com/knewta/r-agent
    tag: v0.1.0
    pullPolicy: IfNotPresent
  pullSecrets: []
  #  - name: aliyun-registry

service:
  type: ClusterIP
  httpPort: 8089
  grpcPort: 9090

server:
  httpAddr: ":8089"
  grpcAddr: ":9090"
  grpcPublicAddr: ""
  publicURL: ""
  logLevel: "info"

database:
  existingSecret:
    name: postgres
    hostKey: R_ORCHESTRATOR_POSTGRES_HOST
    portKey: R_ORCHESTRATOR_POSTGRES_PORT
    dbKey: R_ORCHESTRATOR_POSTGRES_DB
    usernameKey: R_ORCHESTRATOR_POSTGRES_USERNAME
    passwordKey: R_ORCHESTRATOR_POSTGRES_PASSWORD

cluster:
  billingCycleSeconds: 3600
  billingAdvanceSeconds: 180
  agentToken: ""
  agentImage: ""
  agentLogLevel: "info"
  kubernetes:
    enabled: true
    namespace: r-agents
    kubeConfigPath: ""
    imagePullSecrets: []
    #  - name: aliyun-registry

oss:
  endpoint: ""
  accessKeySecret:
    name: aliyun-oss
    key: ALIYUN_OSS_ACCESS_KEY
    secretKey: ALIYUN_OSS_ACCESS_SECRET
  bucket: ""
