// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

type CancelTaskPayload struct {
	TaskID uuid.UUID `json:"task_id"`
	Status string    `json:"status"`
}

type CreateTenantInput struct {
	Name               string `json:"name"`
	PrimaryBackendName string `json:"primary_backend_name"`
	MaxAgents          int    `json:"max_agents"`
}

type Mutation struct {
}

type Query struct {
}

type SubmitTaskInput struct {
	TenantName        string         `json:"tenant_name"`
	RZipFile          graphql.Upload `json:"r_zip_file"`
	ParametersCSVFile graphql.Upload `json:"parameters_csv_file"`
	CompletionHookURL *string        `json:"completion_hook_url,omitempty"`
}

type SubmitTaskResponse struct {
	TaskID uuid.UUID `json:"task_id"`
}

type Task struct {
	ID         uuid.UUID  `json:"id"`
	TenantName string     `json:"tenant_name"`
	Status     string     `json:"status"`
	LastError  string     `json:"last_error"`
	CreatedAt  time.Time  `json:"created_at"`
	StartedAt  *time.Time `json:"started_at,omitempty"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	ShardCount int        `json:"shard_count"`
}

type TaskResultCSV struct {
	TaskID      uuid.UUID `json:"task_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	CSVContent  string    `json:"csv_content"`
}

type Tenant struct {
	ID                 uuid.UUID `json:"id"`
	Name               string    `json:"name"`
	PrimaryBackendName string    `json:"primary_backend_name"`
	MaxAgents          int       `json:"max_agents"`
}
