// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

type CancelTaskPayload struct {
	TaskID uuid.UUID `json:"task_id"`
	Status string    `json:"status"`
}

type CreateTenantInput struct {
	Name               string `json:"name"`
	PrimaryBackendName string `json:"primary_backend_name"`
	MaxAgents          int    `json:"max_agents"`
}

type Mutation struct {
}

type Query struct {
}

type SubmitTaskInput struct {
	TenantName        string         `json:"tenant_name"`
	BundleZip         graphql.Upload `json:"bundle_zip"`
	CompletionHookURL *string        `json:"completion_hook_url,omitempty"`
}

type SubmitTaskResponse struct {
	TaskID uuid.UUID `json:"task_id"`
}

type Task struct {
	ID         uuid.UUID    `json:"id"`
	Status     string       `json:"status"`
	LastError  string       `json:"last_error"`
	CreatedAt  time.Time    `json:"created_at"`
	StartedAt  *time.Time   `json:"started_at,omitempty"`
	FinishedAt *time.Time   `json:"finished_at,omitempty"`
	ShardCount int          `json:"shard_count"`
	Shards     []*TaskShard `json:"shards"`
}

type TaskShard struct {
	ID           uuid.UUID  `json:"id"`
	ScriptName   string     `json:"script_name"`
	Status       string     `json:"status"`
	OutputOssKey *string    `json:"output_oss_key,omitempty"`
	OutputSha256 *string    `json:"output_sha256,omitempty"`
	LastError    *string    `json:"last_error,omitempty"`
	StartedAt    *time.Time `json:"started_at,omitempty"`
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
}

type Tenant struct {
	ID                 uuid.UUID `json:"id"`
	Name               string    `json:"name"`
	PrimaryBackendName string    `json:"primary_backend_name"`
	MaxAgents          int       `json:"max_agents"`
}
