// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ShardAccepted
	//	*AgentMessage_ShardStarted
	//	*AgentMessage_ShardFailed
	//	*AgentMessage_ShardResultReady
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetShardAccepted() *ShardAccepted {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ShardAccepted); ok {
			return x.ShardAccepted
		}
	}
	return nil
}

func (x *AgentMessage) GetShardStarted() *ShardStarted {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ShardStarted); ok {
			return x.ShardStarted
		}
	}
	return nil
}

func (x *AgentMessage) GetShardFailed() *ShardFailed {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ShardFailed); ok {
			return x.ShardFailed
		}
	}
	return nil
}

func (x *AgentMessage) GetShardResultReady() *ShardResultReady {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ShardResultReady); ok {
			return x.ShardResultReady
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ShardAccepted struct {
	ShardAccepted *ShardAccepted `protobuf:"bytes,3,opt,name=shard_accepted,json=shardAccepted,proto3,oneof"`
}

type AgentMessage_ShardStarted struct {
	ShardStarted *ShardStarted `protobuf:"bytes,4,opt,name=shard_started,json=shardStarted,proto3,oneof"`
}

type AgentMessage_ShardFailed struct {
	ShardFailed *ShardFailed `protobuf:"bytes,5,opt,name=shard_failed,json=shardFailed,proto3,oneof"`
}

type AgentMessage_ShardResultReady struct {
	ShardResultReady *ShardResultReady `protobuf:"bytes,6,opt,name=shard_result_ready,json=shardResultReady,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_ShardAccepted) isAgentMessage_Payload() {}

func (*AgentMessage_ShardStarted) isAgentMessage_Payload() {}

func (*AgentMessage_ShardFailed) isAgentMessage_Payload() {}

func (*AgentMessage_ShardResultReady) isAgentMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_AssignShard
	//	*ServerMessage_Drain
	//	*ServerMessage_Shutdown
	//	*ServerMessage_CancelShard
	//	*ServerMessage_ShardResultStored
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetAssignShard() *AssignShard {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_AssignShard); ok {
			return x.AssignShard
		}
	}
	return nil
}

func (x *ServerMessage) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *ServerMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ServerMessage) GetCancelShard() *CancelShard {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CancelShard); ok {
			return x.CancelShard
		}
	}
	return nil
}

func (x *ServerMessage) GetShardResultStored() *ShardResultStored {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ShardResultStored); ok {
			return x.ShardResultStored
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_AssignShard struct {
	AssignShard *AssignShard `protobuf:"bytes,1,opt,name=assign_shard,json=assignShard,proto3,oneof"`
}

type ServerMessage_Drain struct {
	Drain *Drain `protobuf:"bytes,2,opt,name=drain,proto3,oneof"`
}

type ServerMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"`
}

type ServerMessage_CancelShard struct {
	CancelShard *CancelShard `protobuf:"bytes,4,opt,name=cancel_shard,json=cancelShard,proto3,oneof"`
}

type ServerMessage_ShardResultStored struct {
	ShardResultStored *ShardResultStored `protobuf:"bytes,5,opt,name=shard_result_stored,json=shardResultStored,proto3,oneof"`
}

func (*ServerMessage_AssignShard) isServerMessage_Payload() {}

func (*ServerMessage_Drain) isServerMessage_Payload() {}

func (*ServerMessage_Shutdown) isServerMessage_Payload() {}

func (*ServerMessage_CancelShard) isServerMessage_Payload() {}

func (*ServerMessage_ShardResultStored) isServerMessage_Payload() {}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BackendName   string                 `protobuf:"bytes,3,opt,name=backend_name,json=backendName,proto3" json:"backend_name,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Register) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Register) GetBackendName() string {
	if x != nil {
		return x.BackendName
	}
	return ""
}

func (x *Register) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Register) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentShardId string                 `protobuf:"bytes,3,opt,name=current_shard_id,json=currentShardId,proto3" json:"current_shard_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetCurrentShardId() string {
	if x != nil {
		return x.CurrentShardId
	}
	return ""
}

type AssignShard struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShardId         string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	TaskId          string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ScriptName      string                 `protobuf:"bytes,3,opt,name=script_name,json=scriptName,proto3" json:"script_name,omitempty"`
	BundleOssKey    string                 `protobuf:"bytes,4,opt,name=bundle_oss_key,json=bundleOssKey,proto3" json:"bundle_oss_key,omitempty"`
	OutputOssPrefix string                 `protobuf:"bytes,5,opt,name=output_oss_prefix,json=outputOssPrefix,proto3" json:"output_oss_prefix,omitempty"`
	TotalShards     int32                  `protobuf:"varint,6,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssignShard) Reset() {
	*x = AssignShard{}
	mi := &file_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignShard) ProtoMessage() {}

func (x *AssignShard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignShard.ProtoReflect.Descriptor instead.
func (*AssignShard) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{4}
}

func (x *AssignShard) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *AssignShard) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignShard) GetScriptName() string {
	if x != nil {
		return x.ScriptName
	}
	return ""
}

func (x *AssignShard) GetBundleOssKey() string {
	if x != nil {
		return x.BundleOssKey
	}
	return ""
}

func (x *AssignShard) GetOutputOssPrefix() string {
	if x != nil {
		return x.OutputOssPrefix
	}
	return ""
}

func (x *AssignShard) GetTotalShards() int32 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{5}
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_proto_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{6}
}

type CancelShard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShard) Reset() {
	*x = CancelShard{}
	mi := &file_proto_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShard) ProtoMessage() {}

func (x *CancelShard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShard.ProtoReflect.Descriptor instead.
func (*CancelShard) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{7}
}

func (x *CancelShard) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type ShardAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardAccepted) Reset() {
	*x = ShardAccepted{}
	mi := &file_proto_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardAccepted) ProtoMessage() {}

func (x *ShardAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardAccepted.ProtoReflect.Descriptor instead.
func (*ShardAccepted) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{8}
}

func (x *ShardAccepted) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type ShardStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardStarted) Reset() {
	*x = ShardStarted{}
	mi := &file_proto_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardStarted) ProtoMessage() {}

func (x *ShardStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardStarted.ProtoReflect.Descriptor instead.
func (*ShardStarted) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{9}
}

func (x *ShardStarted) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type ShardFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardFailed) Reset() {
	*x = ShardFailed{}
	mi := &file_proto_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardFailed) ProtoMessage() {}

func (x *ShardFailed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardFailed.ProtoReflect.Descriptor instead.
func (*ShardFailed) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{10}
}

func (x *ShardFailed) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardFailed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ShardResultReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	OutputOssKey  string                 `protobuf:"bytes,2,opt,name=output_oss_key,json=outputOssKey,proto3" json:"output_oss_key,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardResultReady) Reset() {
	*x = ShardResultReady{}
	mi := &file_proto_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardResultReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardResultReady) ProtoMessage() {}

func (x *ShardResultReady) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardResultReady.ProtoReflect.Descriptor instead.
func (*ShardResultReady) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{11}
}

func (x *ShardResultReady) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardResultReady) GetOutputOssKey() string {
	if x != nil {
		return x.OutputOssKey
	}
	return ""
}

func (x *ShardResultReady) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ShardResultStored struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardResultStored) Reset() {
	*x = ShardResultStored{}
	mi := &file_proto_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardResultStored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardResultStored) ProtoMessage() {}

func (x *ShardResultStored) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardResultStored.ProtoReflect.Descriptor instead.
func (*ShardResultStored) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{12}
}

func (x *ShardResultStored) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\x18rorchestrator.control.v1\"\xe9\x03\n" +
	"\fAgentMessage\x12@\n" +
	"\bregister\x18\x01 \x01(\v2\".rorchestrator.control.v1.RegisterH\x00R\bregister\x12C\n" +
	"\theartbeat\x18\x02 \x01(\v2#.rorchestrator.control.v1.HeartbeatH\x00R\theartbeat\x12P\n" +
	"\x0eshard_accepted\x18\x03 \x01(\v2'.rorchestrator.control.v1.ShardAcceptedH\x00R\rshardAccepted\x12M\n" +
	"\rshard_started\x18\x04 \x01(\v2&.rorchestrator.control.v1.ShardStartedH\x00R\fshardStarted\x12J\n" +
	"\fshard_failed\x18\x05 \x01(\v2%.rorchestrator.control.v1.ShardFailedH\x00R\vshardFailed\x12Z\n" +
	"\x12shard_result_ready\x18\x06 \x01(\v2*.rorchestrator.control.v1.ShardResultReadyH\x00R\x10shardResultReadyB\t\n" +
	"\apayload\"\x8c\x03\n" +
	"\rServerMessage\x12J\n" +
	"\fassign_shard\x18\x01 \x01(\v2%.rorchestrator.control.v1.AssignShardH\x00R\vassignShard\x127\n" +
	"\x05drain\x18\x02 \x01(\v2\x1f.rorchestrator.control.v1.DrainH\x00R\x05drain\x12@\n" +
	"\bshutdown\x18\x03 \x01(\v2\".rorchestrator.control.v1.ShutdownH\x00R\bshutdown\x12J\n" +
	"\fcancel_shard\x18\x04 \x01(\v2%.rorchestrator.control.v1.CancelShardH\x00R\vcancelShard\x12]\n" +
	"\x13shard_result_stored\x18\x05 \x01(\v2+.rorchestrator.control.v1.ShardResultStoredH\x00R\x11shardResultStoredB\t\n" +
	"\apayload\"\x95\x01\n" +
	"\bRegister\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fbackend_name\x18\x03 \x01(\tR\vbackendName\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"h\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12(\n" +
	"\x10current_shard_id\x18\x03 \x01(\tR\x0ecurrentShardId\"\xd7\x01\n" +
	"\vAssignShard\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vscript_name\x18\x03 \x01(\tR\n" +
	"scriptName\x12$\n" +
	"\x0ebundle_oss_key\x18\x04 \x01(\tR\fbundleOssKey\x12*\n" +
	"\x11output_oss_prefix\x18\x05 \x01(\tR\x0foutputOssPrefix\x12!\n" +
	"\ftotal_shards\x18\x06 \x01(\x05R\vtotalShards\"\a\n" +
	"\x05Drain\"\n" +
	"\n" +
	"\bShutdown\"(\n" +
	"\vCancelShard\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"*\n" +
	"\rShardAccepted\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\")\n" +
	"\fShardStarted\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"M\n" +
	"\vShardFailed\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"k\n" +
	"\x10ShardResultReady\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12$\n" +
	"\x0eoutput_oss_key\x18\x02 \x01(\tR\foutputOssKey\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\".\n" +
	"\x11ShardResultStored\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId2z\n" +
	"\x0eControlService\x12h\n" +
	"\x11OpenControlStream\x12&.rorchestrator.control.v1.AgentMessage\x1a'.rorchestrator.control.v1.ServerMessage(\x010\x01B3Z1github.com/yichozy/r-orchestrator/proto/controlv1b\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_control_proto_goTypes = []any{
	(*AgentMessage)(nil),      // 0: rorchestrator.control.v1.AgentMessage
	(*ServerMessage)(nil),     // 1: rorchestrator.control.v1.ServerMessage
	(*Register)(nil),          // 2: rorchestrator.control.v1.Register
	(*Heartbeat)(nil),         // 3: rorchestrator.control.v1.Heartbeat
	(*AssignShard)(nil),       // 4: rorchestrator.control.v1.AssignShard
	(*Drain)(nil),             // 5: rorchestrator.control.v1.Drain
	(*Shutdown)(nil),          // 6: rorchestrator.control.v1.Shutdown
	(*CancelShard)(nil),       // 7: rorchestrator.control.v1.CancelShard
	(*ShardAccepted)(nil),     // 8: rorchestrator.control.v1.ShardAccepted
	(*ShardStarted)(nil),      // 9: rorchestrator.control.v1.ShardStarted
	(*ShardFailed)(nil),       // 10: rorchestrator.control.v1.ShardFailed
	(*ShardResultReady)(nil),  // 11: rorchestrator.control.v1.ShardResultReady
	(*ShardResultStored)(nil), // 12: rorchestrator.control.v1.ShardResultStored
}
var file_proto_control_proto_depIdxs = []int32{
	2,  // 0: rorchestrator.control.v1.AgentMessage.register:type_name -> rorchestrator.control.v1.Register
	3,  // 1: rorchestrator.control.v1.AgentMessage.heartbeat:type_name -> rorchestrator.control.v1.Heartbeat
	8,  // 2: rorchestrator.control.v1.AgentMessage.shard_accepted:type_name -> rorchestrator.control.v1.ShardAccepted
	9,  // 3: rorchestrator.control.v1.AgentMessage.shard_started:type_name -> rorchestrator.control.v1.ShardStarted
	10, // 4: rorchestrator.control.v1.AgentMessage.shard_failed:type_name -> rorchestrator.control.v1.ShardFailed
	11, // 5: rorchestrator.control.v1.AgentMessage.shard_result_ready:type_name -> rorchestrator.control.v1.ShardResultReady
	4,  // 6: rorchestrator.control.v1.ServerMessage.assign_shard:type_name -> rorchestrator.control.v1.AssignShard
	5,  // 7: rorchestrator.control.v1.ServerMessage.drain:type_name -> rorchestrator.control.v1.Drain
	6,  // 8: rorchestrator.control.v1.ServerMessage.shutdown:type_name -> rorchestrator.control.v1.Shutdown
	7,  // 9: rorchestrator.control.v1.ServerMessage.cancel_shard:type_name -> rorchestrator.control.v1.CancelShard
	12, // 10: rorchestrator.control.v1.ServerMessage.shard_result_stored:type_name -> rorchestrator.control.v1.ShardResultStored
	0,  // 11: rorchestrator.control.v1.ControlService.OpenControlStream:input_type -> rorchestrator.control.v1.AgentMessage
	1,  // 12: rorchestrator.control.v1.ControlService.OpenControlStream:output_type -> rorchestrator.control.v1.ServerMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	file_proto_control_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ShardAccepted)(nil),
		(*AgentMessage_ShardStarted)(nil),
		(*AgentMessage_ShardFailed)(nil),
		(*AgentMessage_ShardResultReady)(nil),
	}
	file_proto_control_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_AssignShard)(nil),
		(*ServerMessage_Drain)(nil),
		(*ServerMessage_Shutdown)(nil),
		(*ServerMessage_CancelShard)(nil),
		(*ServerMessage_ShardResultStored)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
