apiVersion: v1
kind: Secret
metadata:
  name: {{ include "r-orchestrator.fullname" . }}
  labels:
    {{- include "r-orchestrator.labels" . | nindent 4 }}
type: Opaque
data:
  CLUSTER_AGENT_TOKEN: {{ .Values.cluster.agentToken | b64enc | quote }}
