name: DEV

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: dev-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY_NAMESPACE: knewta
  SERVER_IMAGE_NAME: r-orchestrator
  AGENT_IMAGE_NAME: r-agent
  VERSION: ${{ github.ref_name }}
  IMG_ALIYUN_REGISTRY: ${{ vars.ALIYUN_REGISTRY_SG }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Aliyun Registry
        run: echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login --username "${{ secrets.ALIYUN_REGISTRY_USERNAME }}" --password-stdin "${{ env.IMG_ALIYUN_REGISTRY }}"

      - name: Build server image
        run: >
          DOCKER_BUILDKIT=1 docker build
          --file ./Dockerfile.server
          --tag ${{ env.IMG_ALIYUN_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.SERVER_IMAGE_NAME }}:${{ env.VERSION }}
          .

      - name: Push server image
        run: docker push ${{ env.IMG_ALIYUN_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.SERVER_IMAGE_NAME }}:${{ env.VERSION }}

      - name: Build agent image
        run: >
          DOCKER_BUILDKIT=1 docker build
          --file ./Dockerfile.agent
          --tag ${{ env.IMG_ALIYUN_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.AGENT_IMAGE_NAME }}:${{ env.VERSION }}
          .

      - name: Push agent image
        run: docker push ${{ env.IMG_ALIYUN_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.AGENT_IMAGE_NAME }}:${{ env.VERSION }}
